version: '3.1'
services:
  statistics-server:
    build: ewm-statistics-service/statistics-server
    container_name: ewm-statistics-server
    depends_on:
      - statistics-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://statistics-db:5432/statistics-db
      - SPRING_DATASOURCE_USER=statistics
      - SPRING_DATASOURCE_PASSWORD=statistics

  statistics-db:
    image: postgres:14-alpine
    container_name: ewm-statistics-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statistics-db
      - POSTGRES_USER=statistics
      - POSTGRES_PASSWORD=statistics