version: '3.1'
services:
  statistics-server:
    build: ewm-statistics-service/statistics-server
    container_name: ewm-statistics-server
    depends_on:
      - statistics-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://statistics-db:5432/statistics-db
      - SPRING_DATASOURCE_USER=statistics
      - SPRING_DATASOURCE_PASSWORD=statistics

  statistics-db:
    image: postgres:14-alpine
    container_name: ewm-statistics-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statistics-db
      - POSTGRES_USER=statistics
      - POSTGRES_PASSWORD=statistics

  ewm-service:
    build: ewm-main-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm
      - STAT_SERVER_URL=http://statistics-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-service-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm